services:
    imcger.externallinks.listener:
        class: imcger\externallinks\event\main_listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@language'
            - '@request'
        tags:
            - { name: event.listener }
