services:
    imcger.externallinks.admin.controller:
        class: 'imcger\externallinks\controller\admin_controller'
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@request'

    imcger.externallinks.admin.controller.userset:
        class: 'imcger\externallinks\controller\admin_controller_userset'
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@request'
            - '@user'
            - '@dbal.conn'

    imcger.externallinks.listener:
        class: 'imcger\externallinks\event\main_listener'
        arguments:
            - '%core.table_prefix%'
            - '@config'
            - '@user'
            - '@language'
            - '@dbal.conn'
            - '@auth'
            - '@upload_imagesize'
        tags:
            - { name: event.listener }

    imcger.externallinks.ucp:
        class: 'imcger\externallinks\event\ucp_listener'
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@language'
            - '@request'
            - '@dbal.conn'
        tags:
            - { name: event.listener }
